name: Run spammer script on cron schedule

on:
  push:
  schedule:
    - cron: "0,30,45 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm i
      - name: Run Node script
        run: npm start